# See also
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directories:
      - "/"
      - "/base/**/*"
      - "/inputs/**/*"
      - "/research/**/*"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "commonroad-crime"  # only editable installed locally
      - dependency-name: "nuscenes-devkit"  # not installed, just referred to locally via PYTHONPATH
