default_language_version:
    python: python3.10
exclude: '^third_party/'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # run `pre-commit autoupdate` to update the rev below
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.4
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
  - repo: https://github.com/jlebar/pre-commit-hooks
    rev: 6a0c0cbc600e84549e5665cb99a704277526fe18
    hooks:
      - id: bazel-buildifier
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0  # this should correspond to the mypy version in requirements-dev.txt
    hooks:
      - id: mypy
        types: [python]
        args: [--config-file, pyproject.toml, --ignore-missing-imports]
        # args: [--strict] # strict is quite heavy, so disable it for now
