py_library(
    name = "dict_utils",
    srcs = ["dict_utils.py"],
    visibility = ["//visibility:public"],
)

py_test(
    name = "dict_utils_test",
    srcs = ["dict_utils_test.py"],
    deps = [
        ":dict_utils",
        "//:conftest",
    ],
)
